spring:
    application:
        name: usuario-service
    datasource:
        url: jdbc:${CLEARDB_DATABASE_URL}
        driverClassName: com.mysql.jdbc.Driver
        password: ${CLEARDB_DATABASE_PASSWORD}
        username: ${CLEARDB_DATABASE_USERNAME}
        type: com.zaxxer.hikari.HikariDataSource
        hikari:
            maximum-pool-size: 3
            minimum-idle: 1
            connection-test-query: 'SELECT 1'
    jpa:
        hibernate:
            use-new-id-generator-mappings: false
        properties:
            hibernate: {dialect: org.hibernate.dialect.MySQL5InnoDBDialect}

api:
    info:
        title: 'Usuario-Service'
        description: 'Serviço de Usuário para o jogo Luta de Classes'
        version: v1
        termOfService: 'Termos do Serviço'
        contact:
            name: 'Andrews Reis'
            url: null
            email: andrewsdosreis@gmail.com
        license: 'License of Api'
        licenseUrl: null